-- Library Management System Database Schema
-- Auto-generated by Django management command
-- 
-- Generated on: 2026-02-23 21:18:48
-- 

-- Table: auth_group
CREATE TABLE `auth_group` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `auth_group_name_a6ea08ec_uniq` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Indexes for auth_group
ALTER TABLE `auth_group` ADD UNIQUE KEY `auth_group_name_a6ea08ec_uniq` (`name`);

-- Table: auth_group_permissions
CREATE TABLE `auth_group_permissions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `group_id` int NOT NULL,
  `permission_id` int NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `auth_group_permissions_group_id_permission_id_0cd325b0_uniq` (`group_id`,`permission_id`),
  KEY `permission_id` (`permission_id`),
  CONSTRAINT `auth_group_permissions_ibfk_1` FOREIGN KEY (`group_id`) REFERENCES `auth_group` (`id`),
  CONSTRAINT `auth_group_permissions_ibfk_2` FOREIGN KEY (`permission_id`) REFERENCES `auth_permission` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Indexes for auth_group_permissions
ALTER TABLE `auth_group_permissions` ADD KEY `auth_group_permissions_group_id_permission_id_0cd325b0_uniq` (`group_id`, `permission_id`);
ALTER TABLE `auth_group_permissions` ADD KEY `permission_id` (`permission_id`);

-- Table: auth_permission
CREATE TABLE `auth_permission` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `content_type_id` int NOT NULL,
  `codename` varchar(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `auth_permission_content_type_id_codename_01ab375a_uniq` (`content_type_id`,`codename`),
  CONSTRAINT `auth_permission_ibfk_1` FOREIGN KEY (`content_type_id`) REFERENCES `django_content_type` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=53 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Indexes for auth_permission
ALTER TABLE `auth_permission` ADD UNIQUE KEY `auth_permission_content_type_id_codename_01ab375a_uniq` (`content_type_id`, `codename`);

-- Table: auth_user
CREATE TABLE `auth_user` (
  `id` int NOT NULL AUTO_INCREMENT,
  `password` varchar(128) NOT NULL,
  `last_login` datetime(6) DEFAULT NULL,
  `is_superuser` tinyint(1) NOT NULL,
  `username` varchar(150) NOT NULL,
  `first_name` varchar(150) NOT NULL,
  `last_name` varchar(150) NOT NULL,
  `email` varchar(254) NOT NULL,
  `is_staff` tinyint(1) NOT NULL,
  `is_active` tinyint(1) NOT NULL,
  `date_joined` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `auth_user_username_6821ab7c_uniq` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Indexes for auth_user
ALTER TABLE `auth_user` ADD UNIQUE KEY `auth_user_username_6821ab7c_uniq` (`username`);

-- Table: auth_user_groups
CREATE TABLE `auth_user_groups` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `group_id` int NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `auth_user_groups_user_id_group_id_94350c0c_uniq` (`user_id`,`group_id`),
  KEY `group_id` (`group_id`),
  CONSTRAINT `auth_user_groups_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`),
  CONSTRAINT `auth_user_groups_ibfk_2` FOREIGN KEY (`group_id`) REFERENCES `auth_group` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Indexes for auth_user_groups
ALTER TABLE `auth_user_groups` ADD KEY `auth_user_groups_user_id_group_id_94350c0c_uniq` (`user_id`, `group_id`);
ALTER TABLE `auth_user_groups` ADD KEY `group_id` (`group_id`);

-- Table: auth_user_user_permissions
CREATE TABLE `auth_user_user_permissions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `permission_id` int NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `auth_user_user_permissions_user_id_permission_id_14a6b632_uniq` (`user_id`,`permission_id`),
  KEY `permission_id` (`permission_id`),
  CONSTRAINT `auth_user_user_permissions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`),
  CONSTRAINT `auth_user_user_permissions_ibfk_2` FOREIGN KEY (`permission_id`) REFERENCES `auth_permission` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Indexes for auth_user_user_permissions
ALTER TABLE `auth_user_user_permissions` ADD KEY `auth_user_user_permissions_user_id_permission_id_14a6b632_uniq` (`user_id`, `permission_id`);
ALTER TABLE `auth_user_user_permissions` ADD KEY `permission_id` (`permission_id`);

-- Table: django_admin_log
CREATE TABLE `django_admin_log` (
  `id` int NOT NULL AUTO_INCREMENT,
  `action_time` datetime(6) NOT NULL,
  `object_id` longtext,
  `object_repr` varchar(200) NOT NULL,
  `action_flag` smallint unsigned NOT NULL,
  `change_message` longtext NOT NULL,
  `content_type_id` int DEFAULT NULL,
  `user_id` int NOT NULL,
  PRIMARY KEY (`id`),
  KEY `django_admin_log_content_type_id_c4bce8eb_fk_django_co` (`content_type_id`),
  KEY `django_admin_log_user_id_c564eba6_fk_auth_user_id` (`user_id`),
  CONSTRAINT `django_admin_log_ibfk_1` FOREIGN KEY (`content_type_id`) REFERENCES `django_content_type` (`id`),
  CONSTRAINT `django_admin_log_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Indexes for django_admin_log
ALTER TABLE `django_admin_log` ADD KEY `django_admin_log_content_type_id_c4bce8eb_fk_django_co` (`content_type_id`);
ALTER TABLE `django_admin_log` ADD KEY `django_admin_log_user_id_c564eba6_fk_auth_user_id` (`user_id`);

-- Table: django_content_type
CREATE TABLE `django_content_type` (
  `id` int NOT NULL AUTO_INCREMENT,
  `app_label` varchar(100) NOT NULL,
  `model` varchar(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `django_content_type_app_label_model_76bd3d3b_uniq` (`app_label`,`model`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Indexes for django_content_type
ALTER TABLE `django_content_type` ADD UNIQUE KEY `django_content_type_app_label_model_76bd3d3b_uniq` (`app_label`, `model`);

-- Table: django_migrations
CREATE TABLE `django_migrations` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `app` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `applied` datetime(6) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Indexes for django_migrations

-- Table: django_session
CREATE TABLE `django_session` (
  `session_key` varchar(40) NOT NULL,
  `session_data` longtext NOT NULL,
  `expire_date` datetime(6) NOT NULL,
  PRIMARY KEY (`session_key`),
  KEY `django_session_expire_date_a5c62663` (`expire_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Indexes for django_session
ALTER TABLE `django_session` ADD KEY `django_session_expire_date_a5c62663` (`expire_date`);

-- Table: library_admin
CREATE TABLE `library_admin` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `full_name` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `last_login` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`),
  KEY `idx_admin_username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Indexes for library_admin
ALTER TABLE `library_admin` ADD UNIQUE KEY `username` (`username`);
ALTER TABLE `library_admin` ADD KEY `email` (`email`);
ALTER TABLE `library_admin` ADD KEY `idx_admin_username` (`username`);

-- Table: library_author
CREATE TABLE `library_author` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL,
  `bio` text,
  `birth_date` date DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_author_name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Indexes for library_author
ALTER TABLE `library_author` ADD KEY `idx_author_name` (`name`);

-- Table: library_book
CREATE TABLE `library_book` (
  `id` int NOT NULL AUTO_INCREMENT,
  `title` varchar(200) NOT NULL,
  `author_id` int NOT NULL,
  `isbn` varchar(13) NOT NULL,
  `publisher` varchar(200) DEFAULT NULL,
  `publication_year` int DEFAULT NULL,
  `category` varchar(100) DEFAULT NULL,
  `description` text,
  `cover_image` varchar(200) DEFAULT NULL,
  `total_copies` int DEFAULT '1',
  `available_copies` int DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `isbn` (`isbn`),
  KEY `author_id` (`author_id`),
  KEY `idx_book_title` (`title`),
  KEY `idx_book_category` (`category`),
  CONSTRAINT `library_book_ibfk_1` FOREIGN KEY (`author_id`) REFERENCES `library_author` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=51 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Indexes for library_book
ALTER TABLE `library_book` ADD KEY `isbn` (`isbn`);
ALTER TABLE `library_book` ADD KEY `author_id` (`author_id`);
ALTER TABLE `library_book` ADD KEY `idx_book_title` (`title`);
ALTER TABLE `library_book` ADD KEY `idx_book_category` (`category`);

-- Table: library_fine
CREATE TABLE `library_fine` (
  `id` int NOT NULL AUTO_INCREMENT,
  `issue_request_id` bigint DEFAULT NULL,
  `student_id` int NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `days_overdue` int DEFAULT '0',
  `is_paid` tinyint(1) DEFAULT '0',
  `payment_date` timestamp NULL DEFAULT NULL,
  `payment_method` varchar(50) DEFAULT NULL,
  `bkash_payment_id` varchar(100) DEFAULT NULL,
  `bkash_trx_id` varchar(100) DEFAULT NULL,
  `invoice_number` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `description` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `invoice_number` (`invoice_number`),
  KEY `student_id` (`student_id`),
  KEY `idx_fine_paid` (`is_paid`),
  KEY `library_fine_issue_request_id_8d0d75c4` (`issue_request_id`),
  CONSTRAINT `library_fine_ibfk_2` FOREIGN KEY (`student_id`) REFERENCES `library_student` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Indexes for library_fine
ALTER TABLE `library_fine` ADD KEY `invoice_number` (`invoice_number`);
ALTER TABLE `library_fine` ADD KEY `student_id` (`student_id`);
ALTER TABLE `library_fine` ADD KEY `idx_fine_paid` (`is_paid`);
ALTER TABLE `library_fine` ADD KEY `library_fine_issue_request_id_8d0d75c4` (`issue_request_id`);

-- Table: library_issuerequest
CREATE TABLE `library_issuerequest` (
  `id` int NOT NULL AUTO_INCREMENT,
  `book_id` int NOT NULL,
  `student_id` int NOT NULL,
  `request_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `issue_date` date DEFAULT NULL,
  `return_date` date DEFAULT NULL,
  `expected_return_date` date DEFAULT NULL,
  `actual_return_date` date DEFAULT NULL,
  `status` varchar(20) DEFAULT 'requested',
  `notes` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `book_id` (`book_id`),
  KEY `student_id` (`student_id`),
  KEY `idx_issue_status` (`status`),
  CONSTRAINT `library_issuerequest_ibfk_1` FOREIGN KEY (`book_id`) REFERENCES `library_book` (`id`) ON DELETE CASCADE,
  CONSTRAINT `library_issuerequest_ibfk_2` FOREIGN KEY (`student_id`) REFERENCES `library_student` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Indexes for library_issuerequest
ALTER TABLE `library_issuerequest` ADD KEY `book_id` (`book_id`);
ALTER TABLE `library_issuerequest` ADD KEY `student_id` (`student_id`);
ALTER TABLE `library_issuerequest` ADD KEY `idx_issue_status` (`status`);

-- Table: library_notification
CREATE TABLE `library_notification` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `title` varchar(200) NOT NULL,
  `message` longtext NOT NULL,
  `notification_type` varchar(20) NOT NULL,
  `is_read` tinyint(1) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `read_at` datetime(6) DEFAULT NULL,
  `user_id` int NOT NULL,
  PRIMARY KEY (`id`),
  KEY `library_notification_user_id_109bc282_fk_auth_user_id` (`user_id`),
  CONSTRAINT `library_notification_user_id_109bc282_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Indexes for library_notification
ALTER TABLE `library_notification` ADD KEY `library_notification_user_id_109bc282_fk_auth_user_id` (`user_id`);

-- Table: library_student
CREATE TABLE `library_student` (
  `id` int NOT NULL AUTO_INCREMENT,
  `student_id` varchar(20) NOT NULL,
  `username` varchar(50) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `first_name` varchar(100) NOT NULL,
  `last_name` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `phone` varchar(15) DEFAULT NULL,
  `gender` varchar(10) DEFAULT NULL,
  `address` text,
  `date_of_birth` date DEFAULT NULL,
  `department` varchar(100) DEFAULT NULL,
  `enrollment_year` int DEFAULT NULL,
  `profile_image` varchar(200) DEFAULT NULL,
  `status` varchar(20) DEFAULT 'active',
  `is_active` tinyint(1) DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `last_login` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `student_id` (`student_id`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `username` (`username`),
  KEY `idx_student_id` (`student_id`),
  KEY `idx_student_dept` (`department`),
  KEY `idx_student_username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Indexes for library_student
ALTER TABLE `library_student` ADD UNIQUE KEY `student_id` (`student_id`);
ALTER TABLE `library_student` ADD UNIQUE KEY `email` (`email`);
ALTER TABLE `library_student` ADD KEY `username` (`username`);
ALTER TABLE `library_student` ADD KEY `idx_student_id` (`student_id`);
ALTER TABLE `library_student` ADD KEY `idx_student_dept` (`department`);
ALTER TABLE `library_student` ADD KEY `idx_student_username` (`username`);

